GET http://localhost:8080/api/books

####

GET http://localhost:8080/api/books/1

####

POST http://localhost:8080/api/books HTTP/1.1
Content-Type: application/json

{
    "title" : "REST CLIENT BOOK",
    "author" : "John Doe",
    "pages" : 1
}

####

PUT http://localhost:8080/api/books HTTP/1.1
Content-Type: application/json

{
    "id" : 6,
    "title" : "REST CLIENT BOOK 1",
    "author" : "John Doe 2",
    "pages" : 2
}

####

DELETE http://localhost:8080/api/books/5
