services:
  api:
    build:
      context: backend
    container_name: books-api
    image: books-api
    networks:
      - books-network
    ports:
      - "8080:8080"
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: books-nginx
    image: books-nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - books-network
    ports:
      - "8081:80"
    depends_on:
      - api

  frontend:
    # image: node:23-alpine # Replace this with the actual React production build image if needed
    # working_dir: /app
    build:
      context: frontend
    container_name: books-app
    volumes:
      - ./frontend:/app
    command: ["npm", "start"] # For development; replace with "npm run build" for production
    # command: ["npm run build"] # For development; replace with "npm run build" for production
    ports:
      - "3000:3000"
    networks:
      - books-network
    depends_on:
      - api

  db:
    image: postgres
    container_name: books-db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - books-network

networks:
  books-network:
    driver: bridge

volumes:
  pgdata:
