services:
  api:
    build:
      context: ./backend
    image: books-api:latest
    container_name: books-api
    ports:
      - "8080:8080"
    networks:
      - books-network

  nginx:
    build: "./nginx"
    ports:
      - "8081:80"
    depends_on:
      - "api"
    networks:
      - books-network

networks:
  books-network:
    driver: bridge
